// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CustomerSupport struct {
	CsID      uuid.UUID        `json:"cs_id"`
	UserID    uuid.UUID        `json:"user_id"`
	OrderID   uuid.UUID        `json:"order_id"`
	Subject   pgtype.Text      `json:"subject"`
	Message   pgtype.Text      `json:"message"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
