// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCustomerSupportCase(ctx context.Context, arg CreateCustomerSupportCaseParams) (CustomerSupport, error)
	GetCustomerSupportCase(ctx context.Context, csID uuid.UUID) (CustomerSupport, error)
	GetCustomerSupportCaseList(ctx context.Context) ([]CustomerSupport, error)
	UpdateCustomerSupportCaseStatus(ctx context.Context, arg UpdateCustomerSupportCaseStatusParams) (CustomerSupport, error)
}

var _ Querier = (*Queries)(nil)
